- hosts: 7302precommit-worker
  remote_user: '{{ remote_user }}'
  vars:
    - worker_port_0: 3450
    - worker_port_1: 3451
  tasks:
    - debug: var=ansible_default_ipv4.address
    - debug: var=ansible_all_ipv4_addresses[0]
    - debug: var=ansible_hostname
    - name: Remove old worker path
      file:
        path: '{{ item }}'
        state: absent
      loop:
         - '{{ fil_proofs_parent_cache }}'
         - '{{ lotus_worker_path_0 }}'
         - '{{ lotus_worker_path_1 }}'
         - '{{ tmp_dir }}/tmp0'
         - '{{ tmp_dir }}/tmp1'
         - '{{ log_path }}'
    - name: Create cache path, lotus worker path, tmp path, log path
      file:
        path: '{{ item }}'
        state: directory
        owner: '{{ remote_user }}'
        group: '{{ remote_user }}'
        mode: u=rwxr,g=xr,o=x
      loop:
        - '{{ fil_proofs_parent_cache }}'
        - '{{ lotus_worker_path_0 }}'
        - '{{ lotus_worker_path_1 }}'
        - '{{ tmp_dir }}/tmp0'
        - '{{ tmp_dir }}/tmp1'
        - '{{ log_path }}'

    - name: Copy myscheduler config to precommit worker
      copy:
        src: '{{ workspace }}/lotus-ops/config/myscheduler-7302-precommit.json'
        dest: '{{ item }}/myscheduler.json'
      loop:
        - '{{ lotus_worker_path_0 }}'
        - '{{ lotus_worker_path_1 }}'

    - name: Start precommit worker 0
      shell: |
        tmux new -s lotus -d -n worker0
        tmux send-keys -t lotus:worker0 "export FIL_PROOFS_PARAMETER_CACHE={{ fil_proofs_parameter_cache }}" C-m
        tmux send-keys -t lotus:worker0 "export FIL_PROOFS_PARENT_CACHE={{ fil_proofs_parent_cache }}" C-m
        tmux send-keys -t lotus:worker0 "export FIL_PROOFS_USE_MULTICORE_SDR=1" C-m
        tmux send-keys -t lotus:worker0 "export FIL_PROOFS_MAXIMIZE_CACHING=1" C-m
        tmux send-keys -t lotus:worker0 "export FIL_PROOFS_USE_GPU_COLUMN_BUILDER=1" C-m
	      tmux send-keys -t lotus:worker0 "export FIL_PROOFS_USE_GPU_TREE_BUILDER=1" C-m
        tmux send-keys -t lotus:worker0 "export MINER_API_INFO={{ seal_miner_api_info }}" C-m
        tmux send-keys -t lotus:worker0 "export LOTUS_WORKER_PATH={{ lotus_worker_path_0 }}" C-m
        tmux send-keys -t lotus:worker0 "export CUDA_VISIBLE_DEVICES=0" C-m
        tmux send-keys -t lotus:worker0 "export TMPDIR={{ tmp_dir }}/tmp0" C-m
        tmux send-keys -t lotus:worker0 "export FIL_PROOFS_MULTICORE_SDR_CORES=0,32 1,33 2,34 3,35 4,36 5,37 6,38 7,39 8,40 9,41" C-m
        tmux send-keys -t lotus:worker0 "env FIL_PROOFS_MULTICORE_SDR_PRODUCERS=1 FG_ASYNC_IO=0 LOW_RAM_MODE=0 numactl --cpunodebind=0 --membind=0 --physcpubind=10-15,26-31,42-47,58-63 lotus-worker run --listen={{ ansible_all_ipv4_addresses[0] }}:{{ worker_port_0 }} --commit=false" C-m
        tmux pipe-pane -o "cat >>{{ log_path }}/lotus-worker0-`date +%Y-%m-%d-%H-%M`.log"

    - name: Start precommit worker 1
      shell: |
        tmux new-window -t lotus -n worker1
        tmux send-keys -t lotus:worker1 "export FIL_PROOFS_PARAMETER_CACHE={{ fil_proofs_parameter_cache }}" C-m
        tmux send-keys -t lotus:worker1 "export FIL_PROOFS_PARENT_CACHE={{ fil_proofs_parent_cache }}" C-m
        tmux send-keys -t lotus:worker1 "export FIL_PROOFS_MAXIMIZE_CACHING={{ fil_proofs_maximize_caching }}" C-m
        tmux send-keys -t lotus:worker1 "export FIL_PROOFS_USE_GPU_COLUMN_BUILDER={{ fil_proofs_use_gpu_column_builder }}" C-m
	      tmux send-keys -t lotus:worker1 "export FIL_PROOFS_USE_GPU_TREE_BUILDER={{ fil_proofs_use_gpu_tree_builder }}" C-m
        tmux send-keys -t lotus:worker1 "export MINER_API_INFO={{ seal_miner_api_info }}" C-m
        tmux send-keys -t lotus:worker1 "export LOTUS_WORKER_PATH={{ lotus_worker_path_1 }}" C-m
        tmux send-keys -t lotus:worker1 "export CUDA_VISIBLE_DEVICES=1" C-m
        tmux send-keys -t lotus:worker1 "export TMPDIR={{ tmp_dir }}/tmp1" C-m
        tmux send-keys -t lotus:worker0 "export FIL_PROOFS_MULTICORE_SDR_CORES=16,48 17,49 18,50 19,51 20,52 21,53 22,54 23,55 24,56 25,57" C-m
        tmux send-keys -t lotus:worker1 "env FIL_PROOFS_MULTICORE_SDR_PRODUCERS=1 FG_ASYNC_IO=0 LOW_RAM_MODE=0    numactl --cpunodebind=1 --membind=1 --physcpubind=10-15,26-31,42-47,58-63  lotus-worker run --listen={{ ansible_all_ipv4_addresses[0] }}:{{ worker_port_1 }} --commit=false" C-m
        tmux pipe-pane -o "cat >>{{ log_path }}/lotus-worker1-`date +%Y-%m-%d-%H-%M`.log"
