- hosts: 2commit-worker
  remote_user: '{{ remote_user }}'
  vars:
    - worker_port_0: 3450
    - worker_port_1: 3451
  tasks:
    - debug: var=ansible_default_ipv4.address
    - debug: var=ansible_all_ipv4_addresses
    - debug: var=ansible_hostname

    - name: Create lotus worker path, log path, tmp path
      file:
        path: "{{ item }}"
        state: directory
        owner: '{{ remote_user }}'
        group: '{{ remote_user }}'
        mode: u=rwxr,g=xr,o=x
      loop:
        - '{{ lotus_worker_path_0 }}'
        - '{{ lotus_worker_path_1 }}'
        - '{{ log_path }}'
        - '{{ tmp_dir }}/tmp0'
        - '{{ tmp_dir }}/tmp1'

    - name: Copy myscheduler config to commit worker
      copy:
        src: '{{ workspace }}/lotus-ops/config/myscheduler-commit.json'
        dest: '{{ item }}/myscheduler.json'
      loop:
        - '{{ lotus_worker_path_0 }}'
        - '{{ lotus_worker_path_1 }}'

    - name: Start commit worker 0
      shell: |
        tmux new -s lotus -d -n worker0
        tmux send-keys -t lotus:worker0 "export FIL_PROOFS_PARAMETER_CACHE={{ fil_proofs_parameter_cache }}" C-m
        tmux send-keys -t lotus:worker0 "export FIL_PROOFS_PARENT_CACHE={{ fil_proofs_parent_cache }}" C-m
        tmux send-keys -t lotus:worker0 "export FIL_PROOFS_MAXIMIZE_CACHING={{ fil_proofs_maximize_caching }}" C-m
        tmux send-keys -t lotus:worker0 "export FIL_PROOFS_USE_GPU_COLUMN_BUILDER={{ fil_proofs_use_gpu_column_builder }}" C-m
        tmux send-keys -t lotus:worker0 "export FIL_PROOFS_USE_GPU_TREE_BUILDER={{ fil_proofs_use_multicore_sdr }}" C-m
        tmux send-keys -t lotus:worker0 "export MINER_API_INFO={{ seal_miner_api_info2 }}" C-m
        tmux send-keys -t lotus:worker0 "export LOTUS_WORKER_PATH={{ lotus_worker_path_0 }}" C-m
        tmux send-keys -t lotus:worker0 "export CUDA_VISIBLE_DEVICES=0" C-m
        tmux send-keys -t lotus:worker0 "export IPFS_GATEWAY=https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/" C-m
        tmux send-keys -t lotus:worker0 "export TMPDIR={{ tmp_dir }}/tmp0" C-m
        tmux send-keys -t lotus:worker0 "lotus-worker run --listen={{ ansible_all_ipv4_addresses[0] }}:{{ worker_port_0 }} --addpiece=false --precommit1=false --precommit2=false" C-m
        tmux pipe-pane -o "cat >>{{ log_path }}/lotus-worker0-`date +%Y-%m-%d-%H-%M`.log"

    - name: Start commit worker 1
      shell: |
        tmux new-window -t lotus -n worker1
        tmux send-keys -t lotus:worker1 "export FIL_PROOFS_PARAMETER_CACHE={{ fil_proofs_parameter_cache }}" C-m
        tmux send-keys -t lotus:worker1 "export FIL_PROOFS_PARENT_CACHE={{ fil_proofs_parent_cache }}" C-m
        tmux send-keys -t lotus:worker1 "export FIL_PROOFS_MAXIMIZE_CACHING={{ fil_proofs_maximize_caching }}" C-m
        tmux send-keys -t lotus:worker1 "export FIL_PROOFS_USE_GPU_COLUMN_BUILDER={{ fil_proofs_use_gpu_column_builder }}" C-m
        tmux send-keys -t lotus:worker1 "export FIL_PROOFS_USE_GPU_TREE_BUILDER={{ fil_proofs_use_multicore_sdr }}" C-m
        tmux send-keys -t lotus:worker1 "export MINER_API_INFO={{ seal_miner_api_info2 }}" C-m
        tmux send-keys -t lotus:worker1 "export LOTUS_WORKER_PATH={{ lotus_worker_path_1 }}" C-m
        tmux send-keys -t lotus:worker1 "export CUDA_VISIBLE_DEVICES=1" C-m
        tmux send-keys -t lotus:worker1 "export TMPDIR={{ tmp_dir }}/tmp1" C-m
        tmux send-keys -t lotus:worker1 "lotus-worker run --listen={{ ansible_all_ipv4_addresses[0] }}:{{ worker_port_1 }} --addpiece=false --precommit1=false --precommit2=false" C-m
        tmux pipe-pane -o "cat >>{{ log_path }}/lotus-worker1-`date +%Y-%m-%d-%H-%M`.log"

    - name: Start commit worker 2
      shell: |
        tmux new-window -t lotus -n worker2
        tmux send-keys -t lotus:worker2 "export FIL_PROOFS_PARAMETER_CACHE={{ fil_proofs_parameter_cache }}" C-m
        tmux send-keys -t lotus:worker2 "export FIL_PROOFS_PARENT_CACHE={{ fil_proofs_parent_cache }}" C-m
        tmux send-keys -t lotus:worker2 "export FIL_PROOFS_MAXIMIZE_CACHING={{ fil_proofs_maximize_caching }}" C-m
        tmux send-keys -t lotus:worker2 "export FIL_PROOFS_USE_GPU_COLUMN_BUILDER={{ fil_proofs_use_gpu_column_builder }}" C-m
        tmux send-keys -t lotus:worker2 "export FIL_PROOFS_USE_GPU_TREE_BUILDER={{ fil_proofs_use_multicore_sdr }}" C-m
        tmux send-keys -t lotus:worker2 "export MINER_API_INFO={{ seal_miner_api_info2 }}" C-m
        tmux send-keys -t lotus:worker2 "export LOTUS_WORKER_PATH={{ lotus_worker_path_2 }}" C-m
        tmux send-keys -t lotus:worker2 "export CUDA_VISIBLE_DEVICES=2" C-m
        tmux send-keys -t lotus:worker2 "export TMPDIR={{ tmp_dir }}/tmp2" C-m
        tmux send-keys -t lotus:worker2 "lotus-worker run --listen={{ ansible_all_ipv4_addresses[0] }}:{{ worker_port_1 }} --addpiece=false --precommit1=false --precommit2=false" C-m
        tmux pipe-pane -o "cat >>{{ log_path }}/lotus-worker2-`date +%Y-%m-%d-%H-%M`.log"
    
    - name: Start commit worker 3
      shell: |
        tmux new-window -t lotus -n worker3
        tmux send-keys -t lotus:worker3 "export FIL_PROOFS_PARAMETER_CACHE={{ fil_proofs_parameter_cache }}" C-m
        tmux send-keys -t lotus:worker3 "export FIL_PROOFS_PARENT_CACHE={{ fil_proofs_parent_cache }}" C-m
        tmux send-keys -t lotus:worker3 "export FIL_PROOFS_MAXIMIZE_CACHING={{ fil_proofs_maximize_caching }}" C-m
        tmux send-keys -t lotus:worker3 "export FIL_PROOFS_USE_GPU_COLUMN_BUILDER={{ fil_proofs_use_gpu_column_builder }}" C-m
        tmux send-keys -t lotus:worker3 "export FIL_PROOFS_USE_GPU_TREE_BUILDER={{ fil_proofs_use_multicore_sdr }}" C-m
        tmux send-keys -t lotus:worker3 "export MINER_API_INFO={{ seal_miner_api_info2 }}" C-m
        tmux send-keys -t lotus:worker3 "export LOTUS_WORKER_PATH={{ lotus_worker_path_3 }}" C-m
        tmux send-keys -t lotus:worker3 "export CUDA_VISIBLE_DEVICES=3" C-m
        tmux send-keys -t lotus:worker3 "export TMPDIR={{ tmp_dir }}/tmp3" C-m
        tmux send-keys -t lotus:worker3 "lotus-worker run --listen={{ ansible_all_ipv4_addresses[0] }}:{{ worker_port_1 }} --addpiece=false --precommit1=false --precommit2=false" C-m
        tmux pipe-pane -o "cat >>{{ log_path }}/lotus-worker3-`date +%Y-%m-%d-%H-%M`.log"