- hosts: 192.168.3.14
  remote_user: '{{ remote_user }}'
  become: yes
  become_user: root
  become_method: sudo
  vars:
    - lotus_bin_path: 'lotus-bin'
    - version: '1.8.0'
    - platform: 'commit'
  tasks:
    - name: Copy lotus bin to all intel
      copy:
        src: '{{ item }}'
        dest: '/usr/local/bin/'
        mode: +x
      loop:
        - '{{ workspace }}/{{ lotus_bin_path }}/{{ version }}/{{ platform }}/lotus'
        - '{{ workspace }}/{{ lotus_bin_path }}/{{ version }}/{{ platform }}/lotus-miner'
        - '{{ workspace }}/{{ lotus_bin_path }}/{{ version }}/{{ platform }}/lotus-worker'
        - '{{ workspace }}/{{ lotus_bin_path }}/{{ version }}/{{ platform }}/lotus-shed'
